dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: sa-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: sa-webapp
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: sa-logic
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
